import React, { useState } from 'react';
import { Search, FileText, FolderOpen, Download, Filter, CheckCircle2, AlertTriangle } from 'lucide-react';

export default function ReportsView({ patientRecords, onOpenPath }) {
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState('ALL');

  const records = patientRecords || [];

  const filtered = records.filter(r => {
    const matchesSearch = r.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          r.name.toLowerCase().includes(searchQuery.toLowerCase());
    if (!matchesSearch) return false;
    if (filterType === 'REFER') return r.od.includes('Severe') || r.os.includes('Severe') || r.od.includes('Moderate') || r.os.includes('Moderate');
    if (filterType === 'ROUTINE') return r.od.includes('No DR') || r.os.includes('No DR') || r.od.includes('Mild');
    return true;
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {/* Top Controls Header */}
      <div className="ui-card" style={{ padding: '18px 22px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '16px' }}>
          <div>
            <h2 style={{ fontSize: '15px', fontWeight: 800, color: '#17253D' }}>
              Clinical Report Archive
            </h2>
            <p style={{ fontSize: '12px', color: '#60708A', marginTop: '2px' }}>
              Standardized A4 Clinical PDF documents generated by MATLAB reporting engine.
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            {/* Filter Pills */}
            <div style={{ display: 'flex', background: '#EEF3F9', padding: '3px', borderRadius: '10px', border: '1px solid #E0E7F0' }}>
              {['ALL', 'REFER', 'ROUTINE'].map(f => (
                <button
                  key={f}
                  onClick={() => setFilterType(f)}
                  style={{
                    border: 'none',
                    background: filterType === f ? '#F4F7FB' : 'transparent',
                    color: filterType === f ? '#17253D' : '#60708A',
                    fontSize: '11.5px',
                    fontWeight: filterType === f ? 700 : 600,
                    padding: '5px 12px',
                    borderRadius: '8px',
                    cursor: 'pointer',
                    boxShadow: filterType === f ? 'var(--neu-flat-sm)' : 'none'
                  }}
                >
                  {f === 'ALL' ? 'All Reports' : f === 'REFER' ? 'Referrals' : 'Routine'}
                </button>
              ))}
            </div>

            {/* Search Input */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              background: '#EEF3F9',
              boxShadow: 'var(--neu-inset)',
              border: '1px solid #E0E7F0',
              borderRadius: '10px',
              padding: '6px 12px',
              width: '240px'
            }}>
              <Search size={14} color="#8A98AC" />
              <input
                type="text"
                placeholder="Search report by name or ID"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                style={{
                  border: 'none',
                  background: 'transparent',
                  outline: 'none',
                  fontSize: '12px',
                  width: '100%',
                  color: '#17253D',
                  fontFamily: 'var(--font-sans)'
                }}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Reports Table */}
      <div className="ui-card" style={{ padding: '0px', overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
          <thead>
            <tr style={{ background: '#F8FAFD', color: '#60708A', textAlign: 'left', borderBottom: '1px solid #E0E7F0' }}>
              <th style={{ padding: '12px 18px', fontWeight: 700 }}>Report Date</th>
              <th style={{ padding: '12px 18px', fontWeight: 700 }}>Patient Details</th>
              <th style={{ padding: '12px 18px', fontWeight: 700 }}>Right Eye (OD)</th>
              <th style={{ padding: '12px 18px', fontWeight: 700 }}>Left Eye (OS)</th>
              <th style={{ padding: '12px 18px', fontWeight: 700 }}>Triage Decision</th>
              <th style={{ padding: '12px 18px', fontWeight: 700, textAlign: 'right' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((row, idx) => {
              const isReferral = row.od.includes('Severe') || row.os.includes('Severe') || row.od.includes('Moderate') || row.os.includes('Moderate');
              return (
                <tr
                  key={idx}
                  style={{
                    borderBottom: '1px solid #E8EDF4',
                    background: idx % 2 === 0 ? '#F4F7FB' : '#F8FAFD',
                    transition: 'background-color 0.12s ease'
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#F1F5FA'}
                  onMouseLeave={(e) => e.currentTarget.style.backgroundColor = idx % 2 === 0 ? '#F4F7FB' : '#F8FAFD'}
                >
                  <td style={{ padding: '14px 18px', color: '#60708A', fontWeight: 500 }}>
                    {row.date}
                  </td>
                  <td style={{ padding: '14px 18px' }}>
                    <div style={{ fontWeight: 700, color: '#17253D' }}>{row.name}</div>
                    <div style={{ fontSize: '11px', color: '#60708A', marginTop: '2px' }}>{row.id} · {row.ageSex}</div>
                  </td>
                  <td style={{ padding: '14px 18px', fontWeight: 700, color: row.odColor || '#17253D' }}>
                    {row.od}
                  </td>
                  <td style={{ padding: '14px 18px', fontWeight: 700, color: row.osColor || '#17253D' }}>
                    {row.os}
                  </td>
                  <td style={{ padding: '14px 18px' }}>
                    <span style={{
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: '4px',
                      padding: '3px 9px',
                      borderRadius: '12px',
                      fontSize: '11px',
                      fontWeight: 700,
                      background: isReferral ? '#FCE1E3' : '#DDF5EE',
                      border: `1px solid ${isReferral ? '#F6C9CD' : '#bbf7d0'}`,
                      color: isReferral ? '#D94750' : '#28A88A'
                    }}>
                      {isReferral ? <AlertTriangle size={12} /> : <CheckCircle2 size={12} />}
                      {isReferral ? 'Referral Recommended' : 'Routine Follow-up'}
                    </span>
                  </td>
                  <td style={{ padding: '14px 18px', textAlign: 'right' }}>
                    <div style={{ display: 'inline-flex', gap: '8px' }}>
                      <button
                        className="btn btn-outline"
                        onClick={() => onOpenPath(row.pdfPath)}
                        style={{ padding: '5px 12px', fontSize: '11.5px', gap: '5px' }}
                        title="Open Clinical PDF Report"
                      >
                        <FileText size={13} color="#315DAA" />
                        View PDF
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
